version: "3.9"
services:
  web:
    build: ./server
    ports:
      - "8080:8080"
    networks:
      - space
    volumes:
      - ./server:/usr/src/app
    depends_on:
      - "db"
  db:
    image: mariadb
    expose:
      - "3306"
    ports:
      - "3306:3306"
    networks:
      - space
    environment:
      MARIADB_ROOT_PASSWORD: unsafe

networks:
  space:
    driver: bridge